General:
    FILE_NAME: "your_file_name.txt"

Google:
    GOOGLE_CLIENT_SECRET_FILE_NAME: ""
    GOOGLE_SPREADSHEET_ID: ""

Dropbox:
    APP_KEY: ""
    APP_SECRET: ""
    DROPBOX_ACCESS_TOKEN: ""
    DROPBOX_FILE_PATH: "/path/to/your_file_name.txt" # must start with "/"